### ISSUE TITLE
Upgrade Rook to v1.8

### ISSUE THREAD

**Issue by tobru** [projectsyn/component-rook-ceph#27]
## Context

[Rook v1.8.0](https://github.com/rook/rook/releases/tag/v1.8.0) is out. Upgrade it :rocket: 

[Release Blog](https://blog.rook.io/rook-v1-8-storage-enhancements-1407bdd4da4c).

**Comment by simu** [comment]
See also #31, #32, #33

**Comment by simu** [comment]
Upgrade to rook-ceph v1.8.8 / ceph-csi v3.5.1 is done in #48 and #49. Since Rook doesn't officially support skipping minor releases during the upgrade, I think we should make sure this upgrade is rolled out everywhere before we continue with the v1.9 upgrade.

**Comment by tobru** [comment]
[v1.8.9](https://github.com/rook/rook/releases/tag/v1.8.9) just got released, maybe it makes sense to use that one.
