### ISSUE TITLE
Upgrade to Rook v1.9

### ISSUE THREAD

**Issue by simu** [projectsyn/component-rook-ceph#53]
## Context

Upgrade the component to use Rook v1.9 by default. Please note that Rook has updated the bundled Prometheus alerts for 1.9, and we'll need to ensure the runbooks bundled with the component are updated as part of this issue. With the upgrade to Rook 1.9, we should also upgrade the default ceph-csi version to v3.6 as that's the default version which ships with Rook 1.9.

## Out of scope

* Upgrade to Ceph v17

## Acceptance criteria

* Component installs Rook 1.9 by default
* Alert runbooks are upgraded to match the new set of alerts shipped by Rook

**Comment by bastjan** [comment]
Done in #32
